# Site settings
title: *folio
email: james2.huxtable@uwe.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  A simple, portfolio and blogging website
baseurl: /folio/ # the subpath of your site, e.g. /blog/
url: https://huxyuk.github.io/folio # the base hostname & protocol for your site
twitter_username: HuxyUK
github_username:  HuxyUK

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


